version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./todo-backend
    container_name: todo-backend
    depends_on:
      - postgres
    env_file:
      - ./todo-backend/.env
    ports:
      - "3000:3000"
    restart: always

volumes:
  pgdata:
